strawy12/Develofour

Assets/01.Scenes/Yujin/NoticeDataSOFix.unity, Assets/01.Scenes/Yujin/NoticeDataSOFix.unity.meta, Assets/02.Scripts/SO/NoticeDataSO.cs, Assets/02.Scripts/UI/Notice/NoticePanel.cs, Assets/02.Scripts/UI/Notice/NoticeSystem.cs, Assets/03.Prefabs/UI/Windows/NotificationPanel.prefab, Assets/Save/Data.Json, UserSettings/EditorUserSettings.asset
Notice 알람 패널에 이미지 추가함, 데이터 SO에 이미지 넣으면 바뀝니다.
그리고 SO에 들어가는 내용에 따라 패널의 길이가 늘어나게 바꿨습니다.
=> noticepanel 알림창 뜨는거에 이미지 추가

Assets/02.Scripts/UI/Brwoser/Site/Sites/Youtube/YoutubeInteractionButton.cs
=> 좋아요 버튼 버그 수정

Assets/03.Prefabs/UI/TaskBar/TaskBar.prefab, ProjectSettings/TagManager.asset
Window들이 TaskBar를 가리는 오류가 발생
모든 Window들은 TaskBar를 가려서는 안됨
TaskBar에 graphic raycaster와 Canvas를 추가하고
Canvas의 Order in Layer에 WIndow보다 위에있는 Taskbar라는 레이어를 만들어 적용시킴
=> order in layer 수정

Assets/02.Scripts/UI/Window/Windows/Browser.cs
사이트 주소 및 아이콘 브라우저 탑패널에 적용 안되는 오류 해결
=> 브라우저 탑패널 오류 해결

Assets/01.Scenes/Yujin/EmailFavoriteFix.unity, Assets/01.Scenes/Yujin/EmailFavoriteFix.unity.meta, Assets/02.Scripts/Core/Event/EEvent.cs, Assets/02.Scripts/Quest/Decision/Gmail/PoliceMiniGameDecision.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/EmailFavoriteButton.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/EmailSite.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/Mail.cs, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/EmailSite.prefab, Assets/03.Prefabs/UI/Windows/NotificationPanel.prefab, Assets/Save/Data.Json, UserSettings/EditorUserSettings.asset
메일에서 favorite 버튼을 이용해 즐겨찾기 메일을 이용 할 떄,
즐겨찾기 메일 란에서 즐겨찾기 해제시 바로 적용되지 않아 다른 UI에 다녀와야 
해제가 되는 버그를 수정했습니다.
=> favorite 버그 수정했다

Assets/01.Scenes/Yujin/NotUseIconFix.unity, Assets/01.Scenes/Yujin/NotUseIconFix.unity.meta, Assets/02.Scripts/UI/WindowIcon/NotUseIcon.cs, Assets/02.Scripts/UI/WindowIcon/WindowIcon.cs, Assets/03.Prefabs/UI/WindowIcon/WindowIcons.prefab, Assets/Save/Data.Json, UserSettings/EditorUserSettings.asset
배경 화면에서 사용하지 않는 아이콘을 선택했을 때 여러 개 선택이 되면서 
중보 선택이 되는 버그를 수정했다
=> NotUseIcon 선택 버그 수정

Assets/02.Scripts/Core/Data/PlayerData.cs, Assets/02.Scripts/CutScene/News/NewsCutScene.cs, Assets/02.Scripts/UI/Brwoser/FavoriteBar.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Youtube/YoutubeInteractionButton.cs, Assets/02.Scripts/UI/Notice/NoticePanel.cs, Assets/02.Scripts/UI/Notice/NoticeSystem.cs, Assets/02.Scripts/UI/Window/Window.cs, Assets/02.Scripts/UI/Window/Windows/Browser.cs, Assets/02.Scripts/Utils/TouchDragNotice.cs, Assets/10.CustomWindows/Editor/CreateSoundWindow/CreateSoundWindow.cs, Assets/Save/Data.Json
1. 브라우저 중복 실행 버그 수정
2. 싫어요, 좋아요 버튼 브라우저 껐다 켜도 그대로 적용되게 변경
3. static 이벤트 stop 안해준 거 브라우저 관련은 전부 함
4. 쓸데없는 변수 코드 일부 지움
=> Browser fix

Assets/02.Scripts/Core/Data/PlayerData.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/Emails/MailMiniGame/PoliceMiniGame.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/Emails/PoliceMail.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Facebook/FacebookLoginSite.cs, Assets/02.Scripts/UI/Notice/NoticePanel.cs, Assets/02.Scripts/UI/Notice/NoticeSystem.cs
1.noticePanel 여러개 실행 안되게 수정
2.noticePanel 정렬 순서 번경
3.noticePanel 삭제기능 삭제
4.플레이어에 퀘스트데이터 추가(경찰 미니게임 데이터 저장)
=> noticePanel 수정

Assets/01.Scenes/Main.unity, Assets/03.Prefabs/UI/Windows/Browsers/Sites/YoutubeNewsSite.prefab, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_ClearPoliceMinigame.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_EndBrunchPostDelete.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_EndNewsCutScene.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_EnterLoginSite.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_OpenBrunchDeleteMail.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_OpenPoliceMail.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_OpenPoliceReplyMail.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_PressHateButton.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_SnsSetNewPassword.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_SuccessLoginMailSite.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_WriterFacebookLoginSuccess.asset
스크립터블오브젝트 다시 설정함
유튜브 사이트 유튜브 이미지 새로운것으로 변경
=> SettingScriptableObj

Assets/03.Prefabs/UI/Windows/Browsers/Sites/YoutubeNewsSite.prefab
=> 유튜브 이미지 쓸데없는거 삭제

Assets/03.Prefabs/UI/Windows/Browsers/Sites/Brunch/BrunchSite.prefab, Assets/04.Sprites/UI/SearchBoxUI.png.meta, Assets/04.Sprites/UI/SearchExpenBoxUI.png.meta
=> Brunch design fix

Assets/01.Scenes/Yujin/TextBoxUiChange.unity, Assets/01.Scenes/Yujin/TextBoxUiChange.unity.meta, Assets/02.Scripts/CutScene/News/NewsCutScene.cs, Assets/02.Scripts/SO/TextDataSO.cs, Assets/02.Scripts/UI/TextBox/TextBox.cs, Assets/03.Prefabs/UI/TextBox.prefab, Assets/07.ScriptableObjects/Resources/TextData/TextData_News.asset, Assets/Save/Data.Json, UserSettings/EditorUserSettings.asset
=> 텍스트 박스 독백 수정

Assets/01.Scenes/Main.unity, Assets/07.ScriptableObjects/ImageViewerData/ImageViewerDataSO.asset
바탕화면에 이미지 뷰어 아이콘 추가는 했는데 임시라 나중에 바꿔야함
=> 바탕화면에 이미지 뷰어 아이콘 추가는 했는데 임시라 나중에 바꿔야함

Assets/01.Scenes/Main.unity, Assets/02.Scripts/CutScene/News/NewsCutScene.cs, Assets/02.Scripts/CutScene/News/NewsTitle.cs
=> 타이틀 이펙트 추가

Assets/03.Prefabs/UI/Windows/Browsers/Sites/Brunch/BrunchSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/EmailSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Facebook/FacebookLoginSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Facebook/FacebookSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Home/HomeSite.prefab
사이트 URL들 수정
유튜브는 아직 이름이 안정해져있기 때문에 수정안했음
=> Site URL변경

Assets/01.Scenes/Main.unity, Assets/03.Prefabs/UI/TaskBar/TaskBar.prefab, Assets/03.Prefabs/UI/TextBox.prefab, Assets/03.Prefabs/UI/Windows/Browsers/BrowserWindow.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Brunch/BrunchSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/EmailSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Facebook/FacebookSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/LoginSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/YoutubeNewsSite.prefab, Assets/03.Prefabs/UI/Windows/ImageViewer.prefab, Assets/03.Prefabs/UI/Windows/NotePadWindow.prefab, Assets/03.Prefabs/UI/Windows/NotificationPanel.prefab
=> Navigation

Assets/03.Prefabs/UI/TaskBar/TaskBar.prefab
=> taskbar 시간 텍스트 수정

Assets/02.Scripts/UI/Window/Windows/Browser.cs, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Home/HomeSite.prefab, Assets/04.Sprites/UI/SearchExpenBoxUI.png.meta
1.홈 사이트 프리팹 이미지 및 설정 일부 수정
2.브라우저 아이콘 클릭 시 기본으로 홈사이트가 켜져있음
=> Home s ite setting

Assets/01.Scenes/Yujin/WindowLayerFix.unity, Assets/01.Scenes/Yujin/WindowLayerFix.unity.meta, Assets/03.Prefabs/UI/Windows/ImageViewer.prefab, UserSettings/EditorUserSettings.asset
사진 Window 앱은 OrderInLayer가 적용되지 않아 순서가 안 바뀌는 버그 수정했습니다.
=> WindowLayerFix 함

Assets/02.Scripts/Core/Managers/WindowManager.cs, Assets/02.Scripts/CutScene/News/NewsCutScene.cs, Assets/02.Scripts/UI/Window/Windows/Browser.cs, Assets/03.Prefabs/UI/Windows/Browsers/BrowserWindow.prefab
처음 켰을때 youtube 대신 zoogle이 나오는 버그를 수정
=> Url change

Assets/03.Prefabs/UI/Windows/Browsers/BrowserWindow.prefab
병합 오류로 사라진 Chrome 테두리를 다시 집어넣었습니다.
=> 병합 오류로 Chrome 테두리 사라진거 수정

Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/Emails/MailMiniGame/PoliceGameArrow.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/Emails/MailMiniGame/PoliceMiniGame.cs
경찰 출두장 메일 미니게임 인풋 매니저 키 삭제 안되던거 해결 및 함수 변경
=> 메일 인풋 매니저 이슈 해결

Assets/02.Scripts/Core/Sound/BGMPlayer.cs, Assets/02.Scripts/Core/Sound/EffectPlayer.cs, Assets/02.Scripts/Core/Sound/Sound.cs, Assets/02.Scripts/Core/Sound/SoundPlayer.cs, Assets/02.Scripts/CutScene/News/NewsCutScene.cs, Assets/Save/Data.Json
사운드 즉시 종료 코드 작성 
컷씬 스킵시 앵커 목소리 계속 나오는 버그 수정
=> 사운드 즉시 종료 코드 작성 및 컷씬 스킵시 앵커 목소리 계속 나오는 버그 수정

Assets/02.Scripts/UI/Brwoser/Site/Sites/Brunch/BrunchPost.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Brunch/BrunchPostRemoveButton.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Brunch/BrunchPostRemoveButton.cs.meta, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Brunch/BlogPost.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Brunch/BrunchSite.prefab
=> 브런치 글 삭제 버튼 외부 클릭시 꺼지는 것 구현

Assets/01.Scenes/Yujin/StarbookLoginFix.unity, Assets/01.Scenes/Yujin/StarbookLoginFix.unity.meta, Assets/02.Scripts/UI/Brwoser/Site/Sites/Facebook/FacebookLoginSite.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Home/HomeSearchRecord.cs, Assets/Save/Data.Json, UserSettings/EditorUserSettings.asset
스타북 로그인시 갑자기 branch사이트로 돌아가지는 버그 수정
=> 스타북 로그인 버그 수정

Assets/01.Scenes/Yujin/BranchStarbookFix.unity, Assets/01.Scenes/Yujin/BranchStarbookFix.unity.meta, Assets/03.Prefabs/UI/Windows/Browsers/BrowserWindow.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Brunch/BrunchSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Facebook/FacebookSite.prefab, Assets/07.ScriptableObjects/Resources/TextData/TextData_News.asset, Assets/Save/Data.Json
Starbook이 뜨는 즐겨찾기 오류 수정, 한소윤으로 이름 변경
=> 한소윤으로 이름 변경, Starbook 뜨는 곳 픽스

Assets/02.Scripts/Quest/Decision/Gmail/PoliceMiniGameDecision.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/EmailSite.cs, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/EmailSite.prefab
=> 받은 편지함 개수 cnt 증가 기능 추가

Assets/01.Scenes/Main.unity, Assets/02.Scripts/Core/Data/PlayerData.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/Emails/BlogMail.cs, Assets/03.Prefabs/UI/Windows/Browsers/Sites/PoliceMail.prefab, Assets/Save/Data.Json
=> 알림창 스크롤뷰 추가

Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/EmailLine.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/EmailSite.cs, Assets/02.Scripts/UI/Brwoser/Site/Sites/Email/MailDataSO.cs, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/EmailSite.prefab, Assets/07.ScriptableObjects/MailData/Writer/BrunchMail.asset, Assets/07.ScriptableObjects/MailData/Writer/DefaultMail.asset, Assets/07.ScriptableObjects/MailData/Writer/FacebookNewPasswordMail.asset, Assets/07.ScriptableObjects/MailData/Writer/PoliceMail.asset, Assets/07.ScriptableObjects/MailData/Writer/PoliceReplyMail.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterBusinessDummyMail.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail1.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail10.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail11.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail12.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail13.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail2.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail3.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail4.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail5.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail6.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail7.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail8.asset, Assets/07.ScriptableObjects/MailData/Writer/WriterDummyPart1/WriterDummyMail9.asset
=> 사이트 우선 순위 정령 수정

Assets/02.Scripts/UI/Brwoser/Site/Sites/Brunch/BrunchSite.cs, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Brunch/BrunchSite.prefab
text를 inputfield로 바꾸고 readonly를 true로 변경
=> branch 작가 소개 드래그 되게 변경

Assets/02.Scripts/UI/Window/WindowBar.cs
메모장은 창 이동 범위가 설정이 적게 됬더라고
그냥 범위를 50에서 100으로 늘려줬음
=> Quailty up

Assets/01.Scenes/Main.unity, Assets/02.Scripts/CutScene/StartCutScene.cs, Assets/03.Prefabs/UI/CutScene/StartCutScene.prefab
=> Cut scene fix

Assets/01.Scenes/Main.unity, Assets/02.Scripts/CutScene/StartCutScene.cs, Assets/02.Scripts/UI/Notice/NoticePanel.cs, Assets/02.Scripts/UI/Notice/NoticeSystem.cs, Assets/02.Scripts/UI/WindowsLogin/WindowsLockScreen.cs, Assets/03.Prefabs/UI/NotificationPanel.prefab, Assets/03.Prefabs/UI/Windows/Library/FileExplorerWindow.prefab, Assets/07.ScriptableObjects/LibraryData/DirectorySO/User/C/Background/File/Chrome.asset, Assets/07.ScriptableObjects/LibraryData/DirectorySO/User/C/Background/File/Discord.asset, Assets/07.ScriptableObjects/Resources/NoticeData/NoticeData_ConnectUSB.asset, Assets/Save/Data.Json
Notice System에 들어가지않는 버그 수정
fileSO의 가이드 문구 작성
=> Notice 패널 버그 수정

Assets/02.Scripts/UI/Window/Windows/LibraryWindow/FileAddressPanel.cs, Assets/02.Scripts/UI/Window/Windows/LibraryWindow/Library.cs
이벤트 매니저 연결이 파괴된 오브젝트에 연결되어 있어 해제함
=> Library 재실행시 일어나는 오류 해결

Assets/01.Scenes/Main.unity, Assets/02.Scripts/Core/Event/EEvent.cs, Assets/02.Scripts/Core/Event/EventManager.cs, Assets/02.Scripts/Core/Managers/WindowManager.cs, Assets/02.Scripts/UI/Window/Window.cs, Assets/02.Scripts/UI/Window/Windows/LibraryWindow/Library.cs, Assets/02.Scripts/UI/WindowIcon/BackgroundIcon.cs, Assets/02.Scripts/UI/WindowIcon/BackgroundIcon.cs.meta, Assets/02.Scripts/UI/WindowIcon/BackgroundIcons.cs, Assets/02.Scripts/UI/WindowIcon/WindowIcon.cs, Assets/03.Prefabs/UI/WindowIcon/Icons/DefaultIcon.prefab, Assets/07.ScriptableObjects/LibraryData/DirectorySO/User/C/Background/Background.asset
Libaray Icon과 Background 아이콘 구분 완료
=> Library select icon

Assets/01.Scenes/Main.unity, Assets/02.Scripts/UI/Browser/Site/Sites/Facebook/FacebookLoginSite.cs, Assets/02.Scripts/UI/Browser/Site/Sites/GmailLoginSite.cs, Assets/02.Scripts/UI/PasswordInputField/PasswordInputField.cs, Assets/02.Scripts/UI/Window/Windows/Discord/DiscordIdentification.cs, Assets/02.Scripts/UI/Window/Windows/Discord/DiscordLogin.cs, Assets/03.Prefabs/UI/Windows/Discord/DiscordWindow.prefab
=> Facebook and discord enter

Assets/01.Scenes/Yujin/StarbookBugFix.unity, Assets/01.Scenes/Yujin/StarbookBugFix.unity.meta, Assets/02.Scripts/UI/Browser/Site/Sites/Email/Emails/FacebookNewPasswordMail.cs, Assets/02.Scripts/UI/Browser/Site/Sites/Facebook/FacebookLoginSite.cs, Assets/02.Scripts/UI/Browser/Site/Sites/Facebook/FacebookSite.cs, Assets/02.Scripts/UI/Browser/Site/Sites/Facebook/StarbookReset/StarbookPasswordResetSite.cs, Assets/02.Scripts/UI/Window/Windows/Browser.cs, Assets/03.Prefabs/UI/Windows/Browsers/BrowserWindow.prefab, Assets/03.Prefabs/UI/Windows/Browsers/BrowserWindow.prefab.orig.meta, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/EmailSite.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Writer/FacebookNewPassowordMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Facebook/FacebookPasswordResetSIte.prefab, Assets/Save/Data.Json, UserSettings/EditorUserSettings.asset
브라우저 열리긴 함 + 스타북 시스템 과정 중 살짝 디자인 추가
=> Starbook bug fix

Assets/02.Scripts/Tutorial/ProfileTutorial.cs, Assets/02.Scripts/UI/Browser/Site/Sites/Facebook/FacebookLoginSite.cs, Assets/02.Scripts/UI/Window/Windows/Profile/ProfileInfoPanel.cs, Assets/02.Scripts/UI/Window/Windows/Profile/ProfilePanel.cs, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Facebook/FacebookLoginSite.prefab, Assets/03.Prefabs/UI/Windows/Profile/ProfileInfoPanel/OwnerProfileInfoPanel.prefab, Assets/03.Prefabs/UI/Windows/Profile/ProfileWindow.prefab
=> Profile fix

Assets/02.Scripts/Core/Event/EEvent.cs, Assets/02.Scripts/CutScene/StartCutScene.cs, Assets/02.Scripts/SO/TextDataSO.cs, Assets/02.Scripts/Tutorial/ProfileTutorial.cs, Assets/02.Scripts/UI/Monolog/MonologSystem.cs, Assets/02.Scripts/UI/Window/Windows/NotePad/CheckNotePadTyoe.cs, Assets/02.Scripts/UI/WindowIcon/WindowIcon.cs, Assets/07.ScriptableObjects/Resources/TextData/TextData_StartMonolog.asset, Assets/07.ScriptableObjects/Resources/TextData/TextData_StartMonolog.asset.meta
=> tutorialfix

Assets/01.Scenes/Yujin/TextGetWord.unity, Assets/01.Scenes/Yujin/TextGetWord.unity.meta, Assets/02.Scripts/Core/Event/EEvent.cs, Assets/02.Scripts/Core/GetProfilerWordSystem.cs, Assets/02.Scripts/Core/GetProfilerWordSystem.cs.meta, Assets/02.Scripts/UI/Window/Windows/NotePad/NotePadTextGetWord.cs, Assets/02.Scripts/UI/Window/Windows/NotePad/NotePadTextGetWord.cs.meta, Assets/02.Scripts/UI/Window/Windows/Profile/ProfilePanel.cs, Assets/03.Prefabs/UI/Windows/NotePadWindow.prefab, UserSettings/EditorUserSettings.asset
=> 프로파일러 업데이트 구현

Assets/02.Scripts/Core/Managers/WindowManager.cs, Assets/02.Scripts/UI/Notice/NoticePanel.cs, Assets/Save/Data.Json
알람 패널이 강조되는 dotween 효과와 마우스 커서 강조 효과가 중첩되는 버그를 수정했습니다.
=> 알람 패널 마우스 커서 올라갈 시 dotween겹치는거 수정

Assets/01.Scenes/Main.unity, Assets/01.Scenes/Yujin/NotepadCollectionFix.unity, Assets/01.Scenes/Yujin/NotepadCollectionFix.unity.meta, Assets/02.Scripts/Core/GetProfilerWordSystem.cs, Assets/02.Scripts/UI/Window/Windows/NotePad/CheckNotePadTyoe.cs, Assets/03.Prefabs/UI/Windows/Profile/ProfileInfoPanel/OwnerProfileInfoPanel.prefab, Assets/03.Prefabs/UI/Windows/Profile/ProfileWindow.prefab, UserSettings/EditorUserSettings.asset
의뢰인 정보 메모장 단어 클릭 시 단어 수집 가능합니다.
=> Notepad collection fix

Assets/01.Scenes/Garu/discord.unity, Assets/01.Scenes/Main.unity, Assets/02.Scripts/CutScene/StartCutScene.cs, Assets/03.Prefabs/UI/CutScene/StartCutScene.prefab, Assets/03.Prefabs/UI/CutScene/StartCutSceneBackup.prefab, Assets/03.Prefabs/UI/CutScene/StartCutSceneBackup.prefab.meta
=> New cut scene

Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/ADShopPurchaseMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/BranchMemorialMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/DanagaMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/DropcircleMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/FunnyMoneyMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/GYMClosedMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/GyogoBookStoreMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/HealthStoreEventMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/IntRunMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/MunjeoCanvasMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/NevarCompleteMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/NevarWarringMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/NewFitnessCenterOpenMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/OrangeYoungMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/StarbookJoinMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/UkktubePremiumMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/YeonGoHealthMail.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Email/Mails/Dummy/ZooogleNewIPMail.prefab
=> Mail scroll setting

Assets/02.Scripts/UI/TextBox/TextBox.cs, Assets/Save/Data.Json
=> 독백 글자 잘 보이도록 색 수정 완료

Assets/01.Scenes/Main.unity, Assets/02.Scripts/Tutorial/ProfileTutorial.cs, Assets/02.Scripts/UI/Monolog/MonologSystem.cs, Assets/02.Scripts/UI/Window/Windows/Installer/Screen/EndInstallScreen.cs, Assets/02.Scripts/UI/Window/Windows/Profile/Chatting/ProfileChatting.cs, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Facebook/ProfilePanel.prefab, Assets/03.Prefabs/UI/Windows/Profile/ProfileWindow.prefab
=> 확장 축소 변경, 그에 따른 텍스트 width 변경

Assets/01.Scenes/Main.unity, Assets/02.Scripts/SO/Library/FileSO.cs, Assets/02.Scripts/SO/TextDataSO.cs, Assets/02.Scripts/Tutorial/ProfileTutorial.cs, Assets/02.Scripts/Window/Windows/NotePad/Notepad.cs, Assets/07.ScriptableObjects/ImageViewerData/contract.asset, Assets/07.ScriptableObjects/NotepadData/RomeNumber.asset, Assets/07.ScriptableObjects/NotepadData/ZooglePINword.asset, Assets/07.ScriptableObjects/NotepadData/ZooglePassword.asset, Assets/Save/Data.Json
=> 이제 메모장 이미지뷰어 열릴꺼임

Assets/01.Scenes/Main.unity, Assets/Save/Data.Json
=> 속성창 열리는 버그 픽스 완료

Assets/03.Prefabs/UI/Windows/WindowLock/PinLock.prefab
윈도우 잠금 UI 띄우면 클릭 안 되게 하는 Panel 지워서 클릭 되도록 함
=> 윈도우 잠금 UI 띄우고 클릭 되도록 변경

Assets/01.Scenes/Yujin/FileLocationFix.unity, Assets/01.Scenes/Yujin/FileLocationFix.unity.meta, Assets/02.Scripts/Core/Managers/GuideManager.cs, Assets/02.Scripts/Core/Managers/WindowManager.cs, Assets/02.Scripts/SO/Library/FileSO.cs, Assets/02.Scripts/UI/WindowIcon/WindowIcon.cs, Assets/02.Scripts/UI/WindowsLogin/WindowsLockScreen.cs, Assets/02.Scripts/Window/WindowLock/WindowPinInput.cs, Assets/02.Scripts/Window/Windows/LibraryWindow/Library.cs, Assets/02.Scripts/Window/Windows/LibraryWindow/TopFileButton.cs, Assets/02.Scripts/Window/Windows/MediaPlayer/MediaPlayer.cs, Assets/03.Prefabs/UI/Windows/WindowLock/PinLock.prefab, Assets/07.ScriptableObjects/TextData/TextData_StartMonolog.asset, Assets/Save/Data.Json, UserSettings/EditorUserSettings.asset
if문으로 fileName 비교하는 것들 일단 경로로 비교하게 바꿔놧습니다, 튜토리얼 진행 잘 됨
=> FileName으로 비교하는 것들 FileLocation으로 바꿈

Assets/01.Scenes/Main.unity, Assets/03.Prefabs/UI/Windows/Profile/Chatting/ChattingText.prefab, Assets/03.Prefabs/UI/Windows/Profile/ProfileWindow.prefab
=> 프로파일러 폰트 크기 수정 완료

Assets/07.ScriptableObjects/DirectorySO/User/C/Documents/File/Zoogle/ZooglePassword.asset, Assets/Save/Data.Json, UserSettings/EditorUserSettings.asset
Zoogle 패스워드 메모장 여는 Pin에 힌트 추가 헀음
=> Zoogle 메모장 Pin 힌트 추가 완료

Assets/02.Scripts/Tutorial/ProfileTutorial.cs, Assets/Save/Data.Json
=> USB 튜토 구조 변경

Assets/01.Scenes/Main.unity, Assets/02.Scripts/Window/Windows/Profile/ProfileWindow.cs, Assets/03.Prefabs/UI/Windows/Profile/ProfileWindow.prefab, Assets/07.ScriptableObjects/Profile/ProfileInfoData/InfoTextData/Suspect/InfoTextData_SuspectRelationWithVictim.asset
=> 코드 깔끔하게 바꿈.

Assets/02.Scripts/UI/Monolog/MonologSystem.cs
모노로그 텍스트 inputmanager 받을 때 remove안해주던거 고침
=> 디버깅하면서 있던 버그 코드 수정

Assets/01.Scenes/Yujin/InfoFindCursorFix.unity, Assets/01.Scenes/Yujin/InfoFindCursorFix.unity.meta, Assets/02.Scripts/Core/Trigger/GetInformationTrigger.cs, Assets/02.Scripts/Core/Trigger/TextGetWordTrigger.cs, Assets/Save/Data.Json, UserSettings/EditorUserSettings.asset
이미지에서 정보 찾을 때 리스트에 있는거 체크 안 되어있으면 커서 안 바뀜
=> 찾을 수 없는 정보일때 커서 안 바뀜

Assets/01.Scenes/Yujin/HomesearchRecordFix.unity, Assets/02.Scripts/UI/Browser/Site/Sites/Home/HomeSearchRecord.cs, Assets/02.Scripts/UI/Browser/Site/Sites/Home/HomeSite.cs, Assets/03.Prefabs/UI/Windows/Browsers/BrowserWindow.prefab, Assets/03.Prefabs/UI/Windows/Browsers/Sites/Home/HomeSite.prefab, Assets/Save/Data.Json
=> Home info get

Assets/02.Scripts/UI/WindowsLogin/WindowsLoginScreen.cs, Assets/07.ScriptableObjects/TextDataSO/MonologTextDataSO/TextData_USBMonolog.asset, Assets/Save/Data.Json
=> 트리거에 있는 USB 팝업 알림 삭제

Assets/03.Prefabs/UI/Windows/WindowLock/PinLock.prefab
=> pinlock 윈도우 안내 text 수정

Assets/02.Scripts/Core/Managers/GuideManager.cs
=> pin 번호 퀴즈 가이드 쿨타임 늘림

Assets/02.Scripts/Tutorial/GuideButtonTutorial.cs, Assets/02.Scripts/Tutorial/GuideUISystem.cs, Assets/02.Scripts/Tutorial/ProfileSearchTutorial.cs, Assets/02.Scripts/UI/WindowIcon/WindowIcon.cs, Assets/02.Scripts/Window/Windows/LibraryWindow/Library.cs, Assets/02.Scripts/Window/Windows/LibraryWindow/TopFileButton.cs, Assets/02.Scripts/Window/Windows/Profile/Chatting/ProfileGuidePanel.cs, Assets/02.Scripts/Window/Windows/Profile/ProfileWindow.cs, Assets/Save/Data.Json
=> MergyBugFix

Assets/02.Scripts/UI/WindowsLogin/WindowsLockScreen.cs, Assets/02.Scripts/UI/WindowsLogin/WindowsLoginScreen.cs, Assets/Save/Data.Json
=> Start mono log start fix

Assets/02.Scripts/UI/Notice/NoticePanel.cs, Assets/02.Scripts/UI/Notice/NoticeSystem.cs, Assets/02.Scripts/UI/Utils/Debugger.cs, Assets/02.Scripts/Window/Windows/Profile/Chatting/ProfileChattingSystem.cs, Assets/03.Prefabs/UI/NoticePanel.prefab, Assets/Save/Data.Json
노티스에 Icon이 없다면 글자 나오는 것 텍스트 간격 조절
=> Notice panel size fix

Assets/01.Scenes/Main.unity, Assets/10.CustomWindows/Editor/FileSOTools.meta, Assets/10.CustomWindows/Editor/FileSOTools/FileSOTools.uxml, Assets/10.CustomWindows/Editor/FileSOTools/FileSOTools.uxml.meta, Assets/10.CustomWindows/Editor/FileSOTools/FileSOWindow.cs, Assets/10.CustomWindows/Editor/FileSOTools/FileSOWindow.cs.meta
=> 자 툴을 만들었단다

Assets/01.Scenes/Main.unity, Assets/02.Scripts/Call/CallSystem.cs, Assets/Save/Data.Json
=> Request bug fix

Assets/01.Scenes/Main.unity, Assets/03.Prefabs/UI/Windows/Discord/DiscordWindow.prefab, Assets/07.ScriptableObjects/DiscordData/DiscordProfile/AnimalHospital.asset
=> 디스코드, 메인씬 트리거

Assets/02.Scripts/Call/CallSystem.cs
=> 정보를 얻으면 디시젼체크 -> 디시젼체크에서 정보 추가시킴 -> 무한반복

Assets/01.Scenes/Main.unity, Assets/02.Scripts/Core/Data/DataManager/JsonDataManager.cs, Assets/02.Scripts/CutScene/StartCutScene.cs, Assets/02.Scripts/UI/PlayTitle/StartPlayTitleUI.cs, Assets/02.Scripts/UI/WindowsLogin/WindowsLockScreen.cs
=> Start lock fix

Assets/02.Scripts/Window/Windows/Profiler/Chatting/ProfilerChatting.cs, Assets/03.Prefabs/Profiler/ProfilerWindow.prefab
=> Fix tutorial bug

Assets/01.Scenes/Main.unity, Assets/02.Scripts/Utils/Debugger.cs, Assets/02.Scripts/Window/Windows/Profiler/ProfilerAIChatAlarm.cs, Assets/03.Prefabs/Profiler/ProfilerWindow.prefab, Assets/03.Prefabs/UI/TaskBar/TaskIcon.prefab, Assets/03.Prefabs/UI/Windows/Library/WindowFileIconSample.prefab, Assets/07.ScriptableObjects/DirectorySO/AdditionalFile/F_IV_2_OutStarSecurity.asset, Assets/07.ScriptableObjects/DirectorySO/AdditionalFile/F_PF_0_프로파일러.asset, Assets/07.ScriptableObjects/DirectorySO/F_DR_1/F_DR_2/F_DR_5/F_DR_6/F_BR_0_Zoogle.asset, Assets/07.ScriptableObjects/DirectorySO/F_DR_1/F_DR_2/F_DR_5/F_DR_6/F_O_0_OutStarDM.asset
=> Alarm and icon color
